#!/usr/bin/env python3
import json, os

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
fp = os.path.join(base, 'src/data/questions/chapter2.json')

with open(fp, 'r') as f:
    data = json.load(f)

new_q = [
  {"id":"ch2-cvm-008","stem":"CVM 竞价实例（Spot Instance）的特点包括哪些？","options":[{"label":"A","text":"价格比按量计费低 80%-90%"},{"label":"B","text":"当资源池紧张时可能被系统回收"},{"label":"C","text":"适合容错性高的离线批处理任务"},{"label":"D","text":"适合核心数据库等不可中断业务"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-cvm","tags":["CVM","竞价实例","Spot"],"analysis":"竞价实例以极低价格（低80-90%）使用空闲计算资源，但资源紧张时会被2分钟通知后回收。适合大数据分析、CI/CD、渲染等容错任务。D错误，核心业务不应用竞价实例。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.1_%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8CVM%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cvm-009","stem":"CVM 置放群组中分散置放策略的核心目的是什么？","options":[{"label":"A","text":"将实例分散到不同物理机/机架上，降低同时故障风险"},{"label":"B","text":"将实例集中到同一物理机提升性能"},{"label":"C","text":"限制实例的CPU使用率"},{"label":"D","text":"自动进行负载均衡"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cvm","tags":["CVM","置放群组","高可用"],"analysis":"分散置放群组确保实例分布在不同底层物理机/机架上，当某台物理机或机架故障时只影响少量实例。适合高可用场景。与之对应的是集中置放策略（低延迟通信）。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.1_%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8CVM%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cvm-010","stem":"CVM 实例重装系统和重置密码操作有什么风险？","options":[{"label":"A","text":"重装系统会清除系统盘数据，需提前备份"},{"label":"B","text":"重置密码需要关机或重启实例"},{"label":"C","text":"两者都不影响数据盘"},{"label":"D","text":"两者都没有任何风险"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-cvm","tags":["CVM","运维","系统盘"],"analysis":"A重装系统会格式化系统盘，必须提前快照备份；B重置密码在Linux需重启生效；C两者都不影响独立的数据盘。D错误，不提前备份系统盘可能导致数据永久丢失。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.1_%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8CVM%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},

  {"id":"ch2-as-007","stem":"弹性伸缩 AS 支持的伸缩策略类型包括哪些？","options":[{"label":"A","text":"基于监控指标的告警策略（如CPU>70%扩容）"},{"label":"B","text":"定时策略（如每天早9点扩至10台）"},{"label":"C","text":"手动调整期望实例数"},{"label":"D","text":"基于天气预报自动调整"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-as","tags":["AS","伸缩策略"],"analysis":"AS支持三种策略：A告警策略基于云监控指标动态调整；B定时策略按预设时间表扩缩；C手动调整直接修改期望实例数。D AS不支持此类策略。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.2_%E5%BC%B9%E6%80%A7%E4%BC%B8%E7%BC%A9AS%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},
  {"id":"ch2-as-008","stem":"弹性伸缩启动配置中最关键的配置项是？","options":[{"label":"A","text":"镜像ID（指定创建实例使用的基础镜像）"},{"label":"B","text":"实例名称的前缀"},{"label":"C","text":"系统盘的文件系统类型"},{"label":"D","text":"控制台显示的标签颜色"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-as","tags":["AS","启动配置","镜像"],"analysis":"启动配置中镜像ID决定了新创建实例的操作系统和预装软件。最佳实践：使用包含完整应用部署的自定义镜像，确保扩容出的实例可直接对外提供服务。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.2_%E5%BC%B9%E6%80%A7%E4%BC%B8%E7%BC%A9AS%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-as-009","stem":"AS 伸缩组的生命周期钩子（Lifecycle Hook）的作用是？","options":[{"label":"A","text":"在实例启动或终止时暂停伸缩活动，执行自定义操作"},{"label":"B","text":"自动重启实例"},{"label":"C","text":"监控实例的CPU使用率"},{"label":"D","text":"管理实例的安全组规则"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-as","tags":["AS","生命周期钩子"],"analysis":"生命周期钩子在扩容时可暂停实例注册到CLB之前执行初始化脚本（如拉取配置、预热缓存）；缩容时在终止前执行清理操作（如注销服务、备份日志）。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.2_%E5%BC%B9%E6%80%A7%E4%BC%B8%E7%BC%A9AS%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},
  {"id":"ch2-as-010","stem":"AS 伸缩组支持跨可用区部署的目的是什么？","options":[{"label":"A","text":"当某个可用区故障时，其他可用区的实例仍可提供服务"},{"label":"B","text":"提高单个实例的CPU性能"},{"label":"C","text":"降低网络延迟"},{"label":"D","text":"减少实例数量"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-as","tags":["AS","跨可用区","高可用"],"analysis":"AS跨可用区部署自动在多个AZ间分配实例，任一AZ故障时AS自动在其他AZ补足实例，避免单可用区故障导致所有实例不可用。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.2_%E5%BC%B9%E6%80%A7%E4%BC%B8%E7%BC%A9AS%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},

  {"id":"ch2-tke-007","stem":"TKE 中 HPA 和 CA 的关系是？","options":[{"label":"A","text":"HPA 根据指标弹性调整 Pod 数量，CA 根据 Pod 调度需求弹性调整 Node 数量"},{"label":"B","text":"两者功能完全相同"},{"label":"C","text":"HPA 管理节点，CA 管理 Pod"},{"label":"D","text":"两者不能同时使用"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tke","tags":["TKE","HPA","CA","弹性伸缩"],"analysis":"HPA在Pod层面弹性伸缩：根据CPU/内存/自定义指标自动增减Pod副本数。CA在Node层面弹性伸缩：当Pod因资源不足Pending时自动扩容节点。两者配合实现应用+基础设施的双层弹性。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.3_%E5%AE%B9%E5%99%A8%E6%9C%8D%E5%8A%A1TKE%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-tke-008","stem":"TKE 中 Ingress 的作用是什么？","options":[{"label":"A","text":"管理集群外部访问内部 Service 的七层路由规则"},{"label":"B","text":"监控集群节点健康状态"},{"label":"C","text":"管理容器镜像仓库"},{"label":"D","text":"调度 Pod 到指定节点"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tke","tags":["TKE","Ingress","七层路由"],"analysis":"Ingress定义集群的七层入口路由规则，将外部HTTP/HTTPS请求根据域名和URL路径转发到不同的内部Service。TKE的Ingress通常对接CLB实现，支持SSL终止、URL重写等功能。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.3_%E5%AE%B9%E5%99%A8%E6%9C%8D%E5%8A%A1TKE%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-tke-009","stem":"TKE 超级节点（SuperNode）的核心特点是？","options":[{"label":"A","text":"无需管理底层节点，Pod直接运行在弹性资源池上"},{"label":"B","text":"必须购买固定配置的物理服务器"},{"label":"C","text":"仅支持运行系统Pod"},{"label":"D","text":"需要手动管理kubelet进程"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tke","tags":["TKE","超级节点","Serverless"],"analysis":"超级节点是TKE的Serverless能力，Pod无需固定Node即可运行在腾讯云弹性资源池上，按Pod实际使用资源计费。适合突发弹性场景。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.3_%E5%AE%B9%E5%99%A8%E6%9C%8D%E5%8A%A1TKE%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-tke-010","stem":"TKE 集群中 Request 和 Limit 资源配置的最佳实践是？","options":[{"label":"A","text":"Request 设置为应用正常负载的资源需求，Limit 设置为峰值上限"},{"label":"B","text":"Request 和 Limit 都设为 0"},{"label":"C","text":"只设置 Limit 不设置 Request"},{"label":"D","text":"不需要设置任何资源配置"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tke","tags":["TKE","资源管理","QoS"],"analysis":"Request是调度依据（保证最少可用资源），Limit是硬限制（防止无限占用）。设Request=Limit则为Guaranteed QoS，最高优先级不会被驱逐。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.3_%E5%AE%B9%E5%99%A8%E6%9C%8D%E5%8A%A1TKE%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},

  {"id":"ch2-vpc-006","stem":"NAT 网关的主要用途是什么？","options":[{"label":"A","text":"让 VPC 内无公网IP的实例通过NAT网关访问互联网"},{"label":"B","text":"加速VPC间的网络通信"},{"label":"C","text":"提供域名解析服务"},{"label":"D","text":"防御DDoS攻击"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-vpc","tags":["VPC","NAT网关","公网访问"],"analysis":"NAT网关提供SNAT能力，让VPC内私有子网的实例通过NAT网关的EIP访问互联网，无需每个实例绑定公网IP，节省成本且统一出口管理。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.4_%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9CVPC%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},
  {"id":"ch2-vpc-007","stem":"VPC 对等连接和云联网 CCN 的主要区别是什么？","options":[{"label":"A","text":"对等连接是点对点连接，CCN是全网互联的网状网络"},{"label":"B","text":"两者完全一样"},{"label":"C","text":"对等连接支持全网互通，CCN只支持两两连接"},{"label":"D","text":"CCN不支持跨地域连接"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-vpc","tags":["VPC","对等连接","CCN"],"analysis":"对等连接是两个VPC间的点对点连接，N个VPC全互通需N*(N-1)/2条连接。CCN是全网互联架构，所有关联的VPC/IDC自动路由互通，扩展性好，支持跨地域。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.4_%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9CVPC%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-vpc-008","stem":"VPC 中弹性公网 IP（EIP）的特点包括哪些？","options":[{"label":"A","text":"独立的公网IP资源，可与CVM/NAT/CLB等灵活绑定解绑"},{"label":"B","text":"支持在不同实例间迁移不变IP地址"},{"label":"C","text":"按固定月费计费无其他费用"},{"label":"D","text":"未绑定时不产生任何费用"}],"answer":["A","B"],"type":"multiple","chapter":2,"subChapter":"ch2-vpc","tags":["VPC","EIP","弹性公网IP"],"analysis":"A EIP是独立的公网IP资源，可随时绑定/解绑；B可在不同实例间迁移保持IP不变。C EIP支持按带宽或按流量计费；D未绑定EIP时会收取闲置费用。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.4_%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9CVPC%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-vpc-009","stem":"VPC 路由表中优先级最高的路由是？","options":[{"label":"A","text":"最长前缀匹配（CIDR掩码最长）的路由"},{"label":"B","text":"创建时间最早的路由"},{"label":"C","text":"默认路由 0.0.0.0/0"},{"label":"D","text":"手动添加的路由统一最优先"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-vpc","tags":["VPC","路由表","路由优先级"],"analysis":"VPC路由遵循最长前缀匹配原则：掩码越长越精确的路由优先级越高。默认路由0.0.0.0/0是最短前缀，优先级最低。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.4_%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9CVPC%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},
  {"id":"ch2-vpc-010","stem":"混合云场景中 VPC 与 IDC 互通的方式包括哪些？","options":[{"label":"A","text":"VPN 连接（通过IPsec加密隧道经公网互通）"},{"label":"B","text":"专线接入（Direct Connect，专用物理链路）"},{"label":"C","text":"云联网 CCN 统一管理混合云网络"},{"label":"D","text":"直接用公网IP互访即可"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-vpc","tags":["VPC","混合云","VPN","专线"],"analysis":"A VPN连接走公网加密隧道，部署快成本低；B专线接入是物理光纤，高带宽低延迟；C CCN统一管理。D直接公网不安全不推荐。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.4_%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9CVPC%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},

  {"id":"ch2-clb-006","stem":"CLB 后端使用 DPDK 技术的主要优势是什么？","options":[{"label":"A","text":"绕过内核网络协议栈，用户态直接处理数据包，大幅提升转发性能"},{"label":"B","text":"加密数据传输"},{"label":"C","text":"压缩HTTP响应"},{"label":"D","text":"管理SSL证书"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-clb","tags":["CLB","DPDK","高性能"],"analysis":"DPDK让CLB在用户态直接操作网卡收发包，跳过Linux内核协议栈的中断和内存拷贝开销，单实例可实现千万级PPS转发性能。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.5_%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1CLB%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},
  {"id":"ch2-clb-007","stem":"CLB 支持的调度算法包括哪些？","options":[{"label":"A","text":"加权轮询（Weighted Round Robin）"},{"label":"B","text":"加权最小连接数（Weighted Least Connections）"},{"label":"C","text":"源地址哈希（IP Hash）"},{"label":"D","text":"随机选择"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-clb","tags":["CLB","调度算法"],"analysis":"A加权轮询按权重分配（默认）；B加权最小连接数优先转发到连接最少的后端；C源地址哈希固定同一来源IP到同一后端。不支持随机选择。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.5_%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1CLB%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-clb-008","stem":"多可用区 CLB 主可用区故障时会发生什么？","options":[{"label":"A","text":"CLB 自动切换到备可用区继续提供服务"},{"label":"B","text":"CLB 完全不可用需手动切换"},{"label":"C","text":"需要修改DNS才能恢复"},{"label":"D","text":"所有已建立的连接会立即断开且不可恢复"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-clb","tags":["CLB","跨可用区","高可用"],"analysis":"腾讯云CLB支持多可用区部署，当主AZ故障时自动将VIP迁移到备AZ，无需手动干预或修改DNS，实现AZ级高可用。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.5_%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1CLB%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-clb-009","stem":"CLB 的 GSLB 功能解决的是什么问题？","options":[{"label":"A","text":"基于用户地理位置将请求调度到最近的地域，实现跨地域容灾"},{"label":"B","text":"在同一可用区内分发流量"},{"label":"C","text":"压缩HTTP响应数据"},{"label":"D","text":"管理SSL证书续期"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-clb","tags":["CLB","GSLB","跨地域"],"analysis":"GSLB通过DNS智能解析根据用户位置将请求调度到最优地域，同时支持地域级容灾。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.5_%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1CLB%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},
  {"id":"ch2-clb-010","stem":"CLB 的 NAT64 功能解决的核心问题是？","options":[{"label":"A","text":"让 IPv6 客户端访问 IPv4 后端服务器，实现平滑的 IPv6 改造"},{"label":"B","text":"加密网络传输"},{"label":"C","text":"压缩HTTP请求"},{"label":"D","text":"实现DNS解析"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-clb","tags":["CLB","NAT64","IPv6"],"analysis":"NAT64在CLB层将IPv6请求转换为IPv4转发到后端，后端无需改造即可支持IPv6访问。只需CLB配置IPv6 VIP，后端保持IPv4不变。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.5_%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1CLB%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2}
]

data.extend(new_q)
with open(fp, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f'Batch 1: Added {len(new_q)} questions. Chapter2 total: {len(data)}')
