#!/usr/bin/env python3
import json, os

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
fp = os.path.join(base, 'src/data/questions/chapter2.json')

with open(fp, 'r') as f:
    data = json.load(f)

new_q = [
  # ch2-tdsqlc +3
  {"id":"ch2-tdsqlc-006","stem":"TDSQL-C 的\"Log is Database\"理念是什么意思？","options":[{"label":"A","text":"只传输 Redo Log 到存储层，存储层自行回放日志重建数据页，减少网络IO"},{"label":"B","text":"只存储日志不存储数据"},{"label":"C","text":"数据库就是日志服务"},{"label":"D","text":"不需要任何日志"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tdsqlc","tags":["TDSQL-C","Log is Database","架构"],"analysis":"传统数据库需要将脏页和日志都写入存储。TDSQL-C的\"Log is Database\"只将Redo Log传输到共享存储层，存储层异步回放日志重建数据页。这大幅减少了计算层到存储层的网络IO量（减少约90%），是TDSQL-C高性能的关键。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.11_%E4%BA%91%E5%8E%9F%E7%94%9FTDSQL-C%2B%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93Redis/","difficulty":3},
  {"id":"ch2-tdsqlc-007","stem":"TDSQL-C 异地灾备可通过哪种方式实现？","options":[{"label":"A","text":"使用 DTS 数据同步服务将数据实时同步到另一个地域的 TDSQL-C 实例"},{"label":"B","text":"手动定期导出导入SQL"},{"label":"C","text":"无法实现异地灾备"},{"label":"D","text":"通过CDN加速实现"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tdsqlc","tags":["TDSQL-C","DTS","异地灾备"],"analysis":"TDSQL-C可通过DTS数据传输服务实现跨地域数据同步，在目标地域维护一个实时同步的TDSQL-C实例作为灾备。DTS支持全量+增量同步，延迟通常在秒级。发生灾难时将灾备实例提升为主实例。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.11_%E4%BA%91%E5%8E%9F%E7%94%9FTDSQL-C%2B%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93Redis/","difficulty":2},
  {"id":"ch2-tdsqlc-008","stem":"TDSQL-C 和传统 CDB MySQL 在故障恢复时间上的差异是？","options":[{"label":"A","text":"TDSQL-C 秒级恢复（共享存储无需数据复制），CDB 分钟级恢复"},{"label":"B","text":"两者恢复时间相同"},{"label":"C","text":"CDB 恢复更快"},{"label":"D","text":"都不支持故障恢复"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tdsqlc","tags":["TDSQL-C","故障恢复","高可用"],"analysis":"TDSQL-C存算分离架构下主节点故障时，备节点只需接管共享存储层并回放少量Redo Log即可恢复，通常秒级完成。传统CDB需要等待备库完成数据追赶同步，恢复时间通常分钟级。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.11_%E4%BA%91%E5%8E%9F%E7%94%9FTDSQL-C%2B%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93Redis/","difficulty":2},

  # ch2-redis +5
  {"id":"ch2-redis-004","stem":"腾讯云 Redis 集群版的分片机制是什么？","options":[{"label":"A","text":"将 16384 个 Slot 均匀分配到多个分片节点上，通过Key哈希定位分片"},{"label":"B","text":"按时间分片"},{"label":"C","text":"所有数据存储在单个节点"},{"label":"D","text":"按数据大小分片"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-redis","tags":["Redis","集群","Slot"],"analysis":"Redis Cluster将数据空间划分为16384个Slot，每个分片负责一部分Slot。写入Key时通过CRC16(key) mod 16384计算Slot号定位到具体分片。扩容时可在线迁移Slot到新分片。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.12_%E4%BA%91Redis%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%2B%E5%85%B6%E4%BB%96NoSQL/","difficulty":2},
  {"id":"ch2-redis-005","stem":"腾讯云 CKV 磁盘版 Redis 的特点是什么？","options":[{"label":"A","text":"数据持久化存储在磁盘上，容量更大成本更低，适合大容量低频访问场景"},{"label":"B","text":"所有数据只在内存中"},{"label":"C","text":"不支持Redis协议"},{"label":"D","text":"性能比内存版更高"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-redis","tags":["Redis","CKV","磁盘版"],"analysis":"CKV磁盘版将数据持久化到SSD磁盘，热数据缓存在内存中。相比纯内存版：容量可达TB级、成本降低80%，但读写延迟略高。适合数据量大、对延迟不极度敏感的场景如用户画像、历史记录。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.12_%E4%BA%91Redis%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%2B%E5%85%B6%E4%BB%96NoSQL/","difficulty":2},
  {"id":"ch2-redis-006","stem":"Redis 大Key（Big Key）问题的危害和解决方案是什么？","options":[{"label":"A","text":"大Key操作耗时长会阻塞其他请求，应拆分大Key或使用UNLINK异步删除"},{"label":"B","text":"大Key没有任何问题"},{"label":"C","text":"大Key可以提升Redis性能"},{"label":"D","text":"大Key只影响磁盘空间不影响性能"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-redis","tags":["Redis","大Key","性能优化"],"analysis":"大Key（如包含百万元素的Hash/Set）执行操作时耗时长，阻塞Redis主线程影响其他请求。解决方案：1)拆分为多个小Key；2)删除时使用UNLINK而非DEL（异步释放内存）；3)定期扫描识别大Key。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.12_%E4%BA%91Redis%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%2B%E5%85%B6%E4%BB%96NoSQL/","difficulty":2},
  {"id":"ch2-redis-007","stem":"Redis 热Key（Hot Key）问题的处理方案包括哪些？","options":[{"label":"A","text":"使用本地缓存（Local Cache）减少对Redis的访问"},{"label":"B","text":"将热Key复制到多个分片分担读压力"},{"label":"C","text":"对热Key限流保护后端"},{"label":"D","text":"删除热Key即可"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-redis","tags":["Redis","热Key","缓存优化"],"analysis":"A应用侧增加本地缓存（如Guava Cache），极大减少热Key的Redis请求；B读扩展：将热Key复制到多个只读分片；C限流保护防止热Key打爆单分片。D删除热Key会导致大量请求穿透到数据库。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.12_%E4%BA%91Redis%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%2B%E5%85%B6%E4%BB%96NoSQL/","difficulty":3},
  {"id":"ch2-redis-008","stem":"Redis Sorted Set 数据结构的典型应用场景是？","options":[{"label":"A","text":"排行榜（按分数排序快速获取Top N）"},{"label":"B","text":"存储大文件"},{"label":"C","text":"替代关系型数据库"},{"label":"D","text":"日志采集"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-redis","tags":["Redis","Sorted Set","数据结构"],"analysis":"Sorted Set每个元素关联一个分数（score），按分数自动排序。ZRANGEBYSCORE/ZREVRANGE等命令可O(logN+M)获取排名区间。典型场景：游戏排行榜、热门文章排名、延迟队列（score为时间戳）。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.12_%E4%BA%91Redis%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%2B%E5%85%B6%E4%BB%96NoSQL/","difficulty":1},

  # ch2-mq +5
  {"id":"ch2-mq-004","stem":"消息队列在微服务架构中的核心作用包括哪些？","options":[{"label":"A","text":"异步解耦（生产者和消费者独立运行）"},{"label":"B","text":"流量削峰（缓冲突发请求保护下游服务）"},{"label":"C","text":"数据分发（一个消息广播到多个消费者）"},{"label":"D","text":"替代数据库存储数据"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-mq","tags":["消息队列","异步","解耦","削峰"],"analysis":"A异步解耦让上下游服务通过MQ通信互不影响；B削峰缓冲（如秒杀场景请求先入MQ再慢慢消费）；C发布订阅模式实现一对多分发。D MQ不是持久化存储系统，不应替代数据库。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.13_%E6%B6%88%E6%81%AF%E9%98%9F%E5%88%97%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},
  {"id":"ch2-mq-005","stem":"RocketMQ 事务消息的实现流程是？","options":[{"label":"A","text":"发送半消息 → 执行本地事务 → 根据事务结果提交或回滚消息"},{"label":"B","text":"直接发送消息无需事务"},{"label":"C","text":"先消费再生产"},{"label":"D","text":"消息发送后自动执行事务"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-mq","tags":["RocketMQ","事务消息"],"analysis":"RocketMQ事务消息三步：1)发送半消息（Half Message，对消费者不可见）；2)执行本地事务（如扣款）；3)根据本地事务结果发送Commit（消息可消费）或Rollback（丢弃消息）。Broker还有回查机制处理超时未确认的半消息。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.13_%E6%B6%88%E6%81%AF%E9%98%9F%E5%88%97%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},
  {"id":"ch2-mq-006","stem":"CKafka 的消费者组（Consumer Group）机制的作用是？","options":[{"label":"A","text":"同一消费者组内的消费者分担消费Topic的不同Partition，实现负载均衡"},{"label":"B","text":"消费者组内所有消费者都消费全部消息"},{"label":"C","text":"消费者组用来发送消息"},{"label":"D","text":"消费者组限制消息的发送速度"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-mq","tags":["CKafka","消费者组","Partition"],"analysis":"同一Consumer Group内，每个Partition只会分配给一个消费者，实现负载均衡和消息不重复消费。不同Consumer Group各自独立消费全量消息。增加消费者可提升消费吞吐（但不能超过Partition数）。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.13_%E6%B6%88%E6%81%AF%E9%98%9F%E5%88%97%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-mq-007","stem":"消息队列消费失败时的处理策略包括哪些？","options":[{"label":"A","text":"重试机制（按指数退避策略多次重试）"},{"label":"B","text":"死信队列（多次重试失败后转入DLQ人工处理）"},{"label":"C","text":"消费端幂等设计（防止重复消费产生副作用）"},{"label":"D","text":"直接丢弃失败消息"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-mq","tags":["消息队列","重试","死信队列","幂等"],"analysis":"A重试机制处理暂时性故障；B死信队列收集永久失败消息避免阻塞正常消费；C幂等设计确保消息重复消费不会产生重复业务操作。D直接丢弃可能导致数据丢失和业务不一致。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.13_%E6%B6%88%E6%81%AF%E9%98%9F%E5%88%97%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-mq-008","stem":"Pulsar 消息队列相比 Kafka 的架构创新点是？","options":[{"label":"A","text":"存算分离架构（Broker无状态+BookKeeper存储），扩缩容更灵活"},{"label":"B","text":"两者架构完全相同"},{"label":"C","text":"Pulsar不支持持久化"},{"label":"D","text":"Pulsar只能单节点部署"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-mq","tags":["Pulsar","存算分离","消息队列"],"analysis":"Pulsar采用存算分离：Broker（计算层）无状态只负责消息路由，BookKeeper（存储层）负责持久化。扩缩容Broker不需要数据迁移，比Kafka（Broker和存储耦合，扩容需迁移Partition）更灵活。还原生支持多租户。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.13_%E6%B6%88%E6%81%AF%E9%98%9F%E5%88%97%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},

  # ch2-micro +5
  {"id":"ch2-micro-004","stem":"AKF Z 轴扩展指的是？","options":[{"label":"A","text":"按数据分片（如按用户ID哈希分库分表）"},{"label":"B","text":"水平复制增加实例"},{"label":"C","text":"按功能拆分服务"},{"label":"D","text":"按地域部署"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-micro","tags":["微服务","AKF","数据分片"],"analysis":"AKF Z轴扩展是按数据维度分片：如按用户ID哈希将不同用户的数据路由到不同数据库/服务实例。每个分片只处理一部分数据，适合数据量极大的场景。X轴是水平复制，Y轴是功能拆分。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.14_%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%A6%82%E8%BF%B0%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-micro-005","stem":"微服务架构中服务熔断（Circuit Breaker）的作用是？","options":[{"label":"A","text":"当下游服务故障时快速失败，防止级联故障导致整个系统雪崩"},{"label":"B","text":"加速服务间通信"},{"label":"C","text":"加密服务间数据传输"},{"label":"D","text":"自动部署新版本服务"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-micro","tags":["微服务","熔断","Circuit Breaker"],"analysis":"熔断器模式在检测到下游服务连续失败达到阈值时\"断开\"，后续请求直接返回降级结果而不再调用故障服务。这防止了大量超时请求堆积导致调用方也拖垮（级联故障/雪崩效应）。一段时间后半开探测恢复。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.14_%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%A6%82%E8%BF%B0%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-micro-006","stem":"微服务架构中 API 网关的核心功能包括哪些？","options":[{"label":"A","text":"统一入口和路由转发"},{"label":"B","text":"认证鉴权和限流"},{"label":"C","text":"协议转换和日志记录"},{"label":"D","text":"替代所有后端微服务"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-micro","tags":["微服务","API网关"],"analysis":"API网关作为微服务的统一入口：A路由请求到不同服务；B认证（JWT/OAuth）和限流防护；C协议转换（如HTTP转gRPC）和请求日志。D网关不替代后端，只做请求代理和公共能力聚合。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.14_%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%A6%82%E8%BF%B0%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-micro-007","stem":"服务注册与发现机制的工作流程是？","options":[{"label":"A","text":"服务启动时注册到注册中心，调用方从注册中心获取服务地址列表"},{"label":"B","text":"所有服务使用固定IP通信"},{"label":"C","text":"通过DNS轮询实现"},{"label":"D","text":"不需要服务发现直接硬编码地址"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-micro","tags":["微服务","服务注册","服务发现"],"analysis":"微服务动态伸缩场景下IP地址频繁变化。服务注册发现机制：1)服务启动后向注册中心（如Consul/Eureka/Zookeeper）注册自己的地址；2)调用方从注册中心查询目标服务的可用地址列表；3)服务下线或故障时自动注销。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.14_%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%A6%82%E8%BF%B0%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},
  {"id":"ch2-micro-008","stem":"微服务架构中配置中心的核心价值是？","options":[{"label":"A","text":"集中管理所有服务的配置，支持动态更新无需重启服务"},{"label":"B","text":"存储业务数据"},{"label":"C","text":"编译代码"},{"label":"D","text":"管理网络路由"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-micro","tags":["微服务","配置中心"],"analysis":"配置中心集中管理各微服务的配置（数据库连接、开关、限流阈值等），支持动态推送：修改配置后所有相关服务实时生效无需重启。避免了配置散落在各服务中难以管理的问题。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.14_%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%A6%82%E8%BF%B0%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},

  # ch2-scf +5
  {"id":"ch2-scf-004","stem":"SCF 云函数的触发器类型包括哪些？","options":[{"label":"A","text":"API网关触发器（HTTP请求触发）"},{"label":"B","text":"COS触发器（对象存储事件触发）"},{"label":"C","text":"定时触发器（Cron表达式定时执行）"},{"label":"D","text":"物理按钮触发器"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-scf","tags":["SCF","触发器"],"analysis":"SCF支持多种触发器：A API网关将HTTP请求转发到函数处理；B COS触发器在文件上传/删除时触发（如自动处理图片）；C定时触发器按Cron表达式定时执行。D不存在物理按钮触发器。还支持CKafka、CMQ等消息触发器。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.15_Serverless%E4%BA%91%E5%87%BD%E6%95%B0SCF/","difficulty":1},
  {"id":"ch2-scf-005","stem":"SCF 函数的并发控制机制中，预置并发的作用是？","options":[{"label":"A","text":"预先启动指定数量的函数实例常驻，消除冷启动延迟"},{"label":"B","text":"限制函数的最大并发数"},{"label":"C","text":"压缩函数代码"},{"label":"D","text":"加密函数执行环境"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-scf","tags":["SCF","预置并发","冷启动"],"analysis":"预置并发让指定数量的函数实例持续运行不被回收，请求到来时直接使用已初始化的实例处理，完全消除冷启动延迟。适合对延迟敏感的在线业务。预置的实例会持续计费。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.15_Serverless%E4%BA%91%E5%87%BD%E6%95%B0SCF/","difficulty":2},
  {"id":"ch2-scf-006","stem":"SCF 的 Web 函数和事件函数的区别是？","options":[{"label":"A","text":"Web函数原生监听HTTP请求直接返回HTTP响应，事件函数通过JSON事件触发"},{"label":"B","text":"两者完全相同"},{"label":"C","text":"Web函数不支持HTTP"},{"label":"D","text":"事件函数只能处理图片"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-scf","tags":["SCF","Web函数","事件函数"],"analysis":"事件函数接收JSON格式事件参数，适合COS触发、消息触发等场景。Web函数内置HTTP Server直接处理HTTP请求/响应，可将Express/Koa等Web框架直接部署为函数，迁移成本更低。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.15_Serverless%E4%BA%91%E5%87%BD%E6%95%B0SCF/","difficulty":2},
  {"id":"ch2-scf-007","stem":"SCF 函数的执行时间限制和内存限制分别是多少？","options":[{"label":"A","text":"最长执行900秒（15分钟），内存最大支持3072MB"},{"label":"B","text":"无任何限制"},{"label":"C","text":"最长1秒，最大64MB"},{"label":"D","text":"最长24小时，最大1TB"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-scf","tags":["SCF","限制","配置"],"analysis":"SCF函数有资源限制：单次执行最长900秒（15分钟），内存配置范围64MB-3072MB。超过时间限制函数会被强制终止。长时间任务应拆分为多个函数链式调用或使用CVM。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.15_Serverless%E4%BA%91%E5%87%BD%E6%95%B0SCF/","difficulty":1},
  {"id":"ch2-scf-008","stem":"使用 SCF 实现图片处理流水线的架构是怎样的？","options":[{"label":"A","text":"COS上传触发 → SCF函数处理（缩略图/水印/格式转换）→ 结果写回COS"},{"label":"B","text":"在CVM上部署定时脚本轮询"},{"label":"C","text":"在CDN节点上处理图片"},{"label":"D","text":"在数据库中存储图片"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-scf","tags":["SCF","COS触发","图片处理"],"analysis":"典型的事件驱动架构：用户上传图片到COS → COS触发器调用SCF函数 → 函数下载原图执行处理（生成多种尺寸缩略图、添加水印、转WebP格式）→ 处理结果写回COS。全程自动化无需管理服务器，按调用次数计费。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.15_Serverless%E4%BA%91%E5%87%BD%E6%95%B0SCF/","difficulty":2},

  # ch2-domain +4
  {"id":"ch2-domain-005","stem":"腾讯云 DNSPod 智能解析支持的解析策略包括哪些？","options":[{"label":"A","text":"按运营商线路解析（电信/联通/移动返回不同IP）"},{"label":"B","text":"按地域解析（华北/华南返回不同IP）"},{"label":"C","text":"加权轮询（同一域名返回不同IP按权重分配）"},{"label":"D","text":"只支持固定的单条A记录"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-domain","tags":["DNSPod","智能解析","DNS"],"analysis":"DNSPod智能解析：A按运营商线路返回最优IP避免跨网访问；B按地域就近解析降低延迟；C加权轮询实现DNS层面的负载均衡。D错误，DNSPod支持丰富的解析策略。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.16_%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1%2B%E6%95%B0%E5%AD%97%E8%AF%81%E4%B9%A6%2BSSL/","difficulty":2},
  {"id":"ch2-domain-006","stem":"SSL 证书自动续期的重要性是什么？","options":[{"label":"A","text":"证书过期会导致HTTPS不可用，浏览器提示安全风险，严重影响用户信任"},{"label":"B","text":"证书续期仅是费用问题"},{"label":"C","text":"证书过期不会有任何影响"},{"label":"D","text":"只有EV证书需要续期"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-domain","tags":["SSL","证书续期","HTTPS"],"analysis":"SSL证书有有效期（通常1年），过期后浏览器会显示\"不安全\"警告甚至阻止访问，严重影响用户体验和信任。腾讯云支持DV证书自动续期和证书到期前提醒。建议配置自动续期或设置提醒避免证书过期事故。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.16_%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1%2B%E6%95%B0%E5%AD%97%E8%AF%81%E4%B9%A6%2BSSL/","difficulty":1},
  {"id":"ch2-domain-007","stem":"域名备案和域名注册的区别是什么？","options":[{"label":"A","text":"注册是购买域名所有权，备案是向工信部登记网站信息（中国大陆必需）"},{"label":"B","text":"两者是同一件事"},{"label":"C","text":"备案只需要一次永不过期"},{"label":"D","text":"只有.cn域名需要注册"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-domain","tags":["域名","备案","注册"],"analysis":"域名注册是向注册商购买域名使用权。域名备案（ICP备案）是中国特有要求，在中国大陆提供互联网信息服务的网站必须向工信部进行备案登记。未备案的域名不能使用大陆服务器和CDN节点。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.16_%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1%2B%E6%95%B0%E5%AD%97%E8%AF%81%E4%B9%A6%2BSSL/","difficulty":1},
  {"id":"ch2-domain-008","stem":"腾讯云私有域解析 Private DNS 的应用场景是？","options":[{"label":"A","text":"在 VPC 内提供私有域名解析，只对VPC内资源可见，不暴露到公网"},{"label":"B","text":"替代公网DNS"},{"label":"C","text":"加速CDN"},{"label":"D","text":"管理SSL证书"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-domain","tags":["Private DNS","私有域名","VPC"],"analysis":"Private DNS在VPC内提供自定义域名解析（如db.internal.company.com → 10.0.1.100），方便服务间用域名而非IP访问。域名解析只对关联VPC可见，不暴露到公网，提高安全性。修改后端IP时只需改DNS记录，无需改应用配置。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.16_%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1%2B%E6%95%B0%E5%AD%97%E8%AF%81%E4%B9%A6%2BSSL/","difficulty":2},

  # ch2-tcop +3
  {"id":"ch2-tcop-006","stem":"TCOP 中 APM（应用性能监控）的核心能力是？","options":[{"label":"A","text":"自动发现应用拓扑，监控接口响应时间、错误率和吞吐量"},{"label":"B","text":"仅监控CPU使用率"},{"label":"C","text":"管理应用代码版本"},{"label":"D","text":"自动修复应用bug"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tcop","tags":["TCOP","APM","应用监控"],"analysis":"APM（Application Performance Monitoring）通过在应用中植入探针自动采集：1)服务拓扑（微服务间调用关系）；2)接口级性能（响应时间/错误率/QPS）；3)慢请求详情和异常堆栈。帮助快速定位性能瓶颈和故障根因。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.17_%E8%85%BE%E8%AE%AF%E4%BA%91%E5%8F%AF%E8%A7%82%E6%B5%8B%E5%B9%B3%E5%8F%B0/","difficulty":2},
  {"id":"ch2-tcop-007","stem":"可观测平台中 SLI/SLO/SLA 的关系是？","options":[{"label":"A","text":"SLI 是可量化的服务指标，SLO 是目标值，SLA 是与客户的正式承诺"},{"label":"B","text":"三者含义完全相同"},{"label":"C","text":"SLA 是内部指标，SLO 是外部承诺"},{"label":"D","text":"只有SLA有实际意义"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tcop","tags":["TCOP","SLI","SLO","SLA"],"analysis":"SLI（Service Level Indicator）：可量化的服务质量指标（如可用性99.95%、P99延迟<200ms）。SLO（Service Level Objective）：SLI的内部目标值。SLA（Service Level Agreement）：与客户签订的正式服务承诺，通常包含违约赔偿。SLO应严于SLA留有余量。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.17_%E8%85%BE%E8%AE%AF%E4%BA%91%E5%8F%AF%E8%A7%82%E6%B5%8B%E5%B9%B3%E5%8F%B0/","difficulty":2},
  {"id":"ch2-tcop-008","stem":"Grafana 在可观测体系中的角色是什么？","options":[{"label":"A","text":"数据可视化平台，将 Prometheus/CLS 等数据源以图表和 Dashboard 形式展示"},{"label":"B","text":"数据采集Agent"},{"label":"C","text":"日志存储系统"},{"label":"D","text":"代码部署工具"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tcop","tags":["TCOP","Grafana","可视化"],"analysis":"Grafana是开源的数据可视化平台，支持对接Prometheus、CLS、MySQL等多种数据源，通过丰富的图表类型（折线图、热力图、表格等）构建实时监控Dashboard。TCOP内置Grafana服务，免去自建维护成本。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.17_%E8%85%BE%E8%AE%AF%E4%BA%91%E5%8F%AF%E8%A7%82%E6%B5%8B%E5%B9%B3%E5%8F%B0/","difficulty":1}
]

data.extend(new_q)
with open(fp, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f'Batch 3: Added {len(new_q)} questions. Chapter2 total: {len(data)}')
