#!/usr/bin/env python3
import json, os

base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
fp = os.path.join(base, 'src/data/questions/chapter2.json')

with open(fp, 'r') as f:
    data = json.load(f)

new_q = [
  # ch2-cdn +5
  {"id":"ch2-cdn-006","stem":"ECDN（全站加速）相比传统 CDN 的核心区别是？","options":[{"label":"A","text":"ECDN 支持动态内容加速，通过智能路由优化回源链路"},{"label":"B","text":"两者完全一样"},{"label":"C","text":"ECDN 不支持静态内容缓存"},{"label":"D","text":"ECDN 只能在中国大陆使用"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdn","tags":["ECDN","全站加速","动态加速"],"analysis":"传统CDN主要加速可缓存的静态内容。ECDN（Enterprise CDN/全站加速）在静态缓存基础上增加了动态内容加速能力：通过智能路由选择最优回源路径、持久连接复用、协议优化等技术加速API请求等动态内容。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.6_%E5%86%85%E5%AE%B9%E5%88%86%E5%8F%91%E7%BD%91%E7%BB%9CCDN%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cdn-007","stem":"CDN URL 鉴权（防盗链）的实现原理是？","options":[{"label":"A","text":"在 URL 中携带加密签名参数，CDN 验证签名有效性和过期时间"},{"label":"B","text":"仅检查 HTTP Referer 头"},{"label":"C","text":"检查用户的 IP 地址"},{"label":"D","text":"要求用户输入密码"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdn","tags":["CDN","URL鉴权","防盗链"],"analysis":"URL鉴权通过在资源URL中附加签名参数（如 ?sign=md5(key+path+expire)&t=timestamp），CDN节点验证签名正确性和时间戳是否过期。相比Referer防盗链更安全，可有效防止URL被盗用。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.6_%E5%86%85%E5%AE%B9%E5%88%86%E5%8F%91%E7%BD%91%E7%BB%9CCDN%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cdn-008","stem":"CDN 中间源（Mid-tier）的作用是什么？","options":[{"label":"A","text":"在边缘节点和源站之间增加一层缓存，减少回源请求集中打到源站"},{"label":"B","text":"替代源站存储数据"},{"label":"C","text":"加密所有传输内容"},{"label":"D","text":"管理域名解析"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdn","tags":["CDN","中间源","回源优化"],"analysis":"中间源是CDN的二级缓存层，多个边缘节点共享同一中间源。当边缘缓存未命中时先查中间源，中间源未命中才回源站。这大幅减少了源站压力，尤其在热点资源场景下效果显著。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.6_%E5%86%85%E5%AE%B9%E5%88%86%E5%8F%91%E7%BD%91%E7%BB%9CCDN%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cdn-009","stem":"CDN HTTPS 加速需要配置什么？","options":[{"label":"A","text":"在CDN控制台上传SSL证书并绑定加速域名"},{"label":"B","text":"只需在源站配置HTTPS"},{"label":"C","text":"CDN默认支持HTTPS无需配置"},{"label":"D","text":"需要在每个边缘节点手动安装证书"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdn","tags":["CDN","HTTPS","SSL证书"],"analysis":"CDN HTTPS加速需要在CDN控制台为加速域名配置SSL证书（可使用腾讯云SSL证书服务的免费证书或自有证书）。CDN节点使用该证书与客户端建立HTTPS连接，回源可选HTTP或HTTPS。证书管理由CDN平台统一处理，无需逐节点操作。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.6_%E5%86%85%E5%AE%B9%E5%88%86%E5%8F%91%E7%BD%91%E7%BB%9CCDN%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},
  {"id":"ch2-cdn-010","stem":"IGTM（智能全局流量管理）在CDN场景中的作用是？","options":[{"label":"A","text":"根据健康检查和调度策略将用户请求分配到最优的CDN入口或源站"},{"label":"B","text":"压缩网页图片"},{"label":"C","text":"管理SSL证书"},{"label":"D","text":"加速数据库查询"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdn","tags":["CDN","IGTM","流量管理"],"analysis":"IGTM通过健康检查监控多个CDN入口/源站的可用性，结合地理位置、延迟等策略智能调度流量。当某条线路或源站故障时自动切换到备用线路，实现业务高可用和流量最优调度。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.6_%E5%86%85%E5%AE%B9%E5%88%86%E5%8F%91%E7%BD%91%E7%BB%9CCDN%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},

  # ch2-storage +4
  {"id":"ch2-storage-007","stem":"COS 智能分层存储的工作原理是什么？","options":[{"label":"A","text":"根据对象的访问频率自动在标准层和低频层之间流转，无需人工干预"},{"label":"B","text":"将所有数据存储在最低成本层"},{"label":"C","text":"按文件大小自动分层"},{"label":"D","text":"只在创建时选择存储类型，之后不可改变"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-storage","tags":["COS","智能分层","存储优化"],"analysis":"智能分层存储自动监控对象访问频率：频繁访问的保持在标准层（高性能），一段时间未访问的自动降为低频层（低成本）。再次访问时自动提升回标准层。适合访问模式不确定的数据，兼顾性能和成本。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.7_%E4%BA%91%E5%AD%98%E5%82%A8%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-storage-008","stem":"COS 数据冗余使用的纠删码技术相比多副本的优势是？","options":[{"label":"A","text":"同等可靠性下存储开销更低（如1.5倍vs3倍）"},{"label":"B","text":"读取速度更快"},{"label":"C","text":"不需要任何冗余数据"},{"label":"D","text":"只适用于小文件"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-storage","tags":["COS","纠删码","数据冗余"],"analysis":"纠删码（Erasure Coding）将数据分片后生成校验片，通过数学算法实现数据恢复。相比三副本（3x存储开销），纠删码只需约1.5x存储开销即可达到相同或更高的可靠性（如12个9的持久性）。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.7_%E4%BA%91%E5%AD%98%E5%82%A8%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},
  {"id":"ch2-storage-009","stem":"存储网关 CSG 的应用场景是什么？","options":[{"label":"A","text":"在本地环境通过NFS/SMB协议访问云端COS存储，实现混合云存储"},{"label":"B","text":"仅用于备份本地硬盘"},{"label":"C","text":"替代所有本地存储设备"},{"label":"D","text":"加速CPU计算"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-storage","tags":["CSG","存储网关","混合云"],"analysis":"CSG（Cloud Storage Gateway）在本地部署网关设备，将COS对象存储映射为本地NFS/SMB文件系统。应用无需改造即可通过标准文件协议读写云端数据。适合混合云场景：本地热数据缓存+云端海量冷存储。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.7_%E4%BA%91%E5%AD%98%E5%82%A8%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-storage-010","stem":"CFS 文件存储相比 CBS 块存储的核心区别是？","options":[{"label":"A","text":"CFS 支持多个CVM实例同时挂载同一文件系统读写共享数据"},{"label":"B","text":"CFS 的IOPS性能更高"},{"label":"C","text":"CFS 只能存储图片"},{"label":"D","text":"两者没有区别"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-storage","tags":["CFS","CBS","共享存储"],"analysis":"CFS基于NFS/CIFS协议提供共享文件系统，多个CVM可同时挂载读写同一份数据（如共享配置文件、日志目录）。CBS是块存储，普通类型只能挂载到单个CVM。CFS适合需要多实例共享数据的场景。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.7_%E4%BA%91%E5%AD%98%E5%82%A8%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":1},

  # ch2-cls +3
  {"id":"ch2-cls-006","stem":"LogListener 采集日志的内部机制中，使用 inotify 的目的是什么？","options":[{"label":"A","text":"实时监听文件变化事件，发现新日志写入时立即采集，避免轮询开销"},{"label":"B","text":"压缩日志文件"},{"label":"C","text":"加密日志传输"},{"label":"D","text":"管理日志主题"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cls","tags":["CLS","LogListener","inotify"],"analysis":"LogListener使用Linux inotify机制监听日志文件的IN_MODIFY事件，当应用写入新日志时内核立即通知LogListener读取增量数据。相比定期轮询（polling），inotify是事件驱动的，CPU开销更低且实时性更好。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.8_%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1CLS%E4%BB%8B%E7%BB%8D/","difficulty":3},
  {"id":"ch2-cls-007","stem":"CLS 日志主题（Topic）的 partition 分区有什么作用？","options":[{"label":"A","text":"将日志数据分散到多个分区并行写入和消费，提高吞吐量"},{"label":"B","text":"加密日志数据"},{"label":"C","text":"压缩日志体积"},{"label":"D","text":"自动删除过期日志"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cls","tags":["CLS","Topic","分区"],"analysis":"CLS日志主题的分区（Partition）类似Kafka的Partition概念，日志数据按哈希分散到多个分区并行写入和消费。分区数决定了写入和消费的并发度，业务量大时可增加分区数提升吞吐。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.8_%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1CLS%E4%BB%8B%E7%BB%8D/","difficulty":2},
  {"id":"ch2-cls-008","stem":"LogListener 采集进度管理中 checkpoint 机制的作用是？","options":[{"label":"A","text":"记录每个日志文件的采集位置，Agent重启后从断点继续采集避免重复或丢失"},{"label":"B","text":"压缩日志文件"},{"label":"C","text":"加密日志内容"},{"label":"D","text":"限制日志文件大小"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cls","tags":["CLS","LogListener","checkpoint"],"analysis":"checkpoint记录每个被采集文件的inode和已读取偏移量（offset）。当LogListener重启或异常恢复时，从checkpoint记录的位置继续读取，确保不重复采集已处理的日志，也不遗漏新增的日志。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.8_%E6%97%A5%E5%BF%97%E6%9C%8D%E5%8A%A1CLS%E4%BB%8B%E7%BB%8D/","difficulty":3},

  # ch2-cdb +5
  {"id":"ch2-cdb-004","stem":"CDB MySQL 数据库代理（Database Proxy）的核心功能是什么？","options":[{"label":"A","text":"自动将读请求分发到只读实例，写请求路由到主实例，应用无需修改代码"},{"label":"B","text":"备份数据库数据"},{"label":"C","text":"加速SQL查询执行"},{"label":"D","text":"管理数据库用户权限"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdb","tags":["CDB","数据库代理","读写分离"],"analysis":"数据库代理是CDB的读写分离中间层，应用只需连接代理地址，代理自动识别SQL类型：SELECT等读请求分发到只读实例，INSERT/UPDATE/DELETE等写请求路由到主实例。透明实现读写分离无需改代码。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.9_%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cdb-005","stem":"CDB MySQL 慢查询优化的常见方法包括哪些？","options":[{"label":"A","text":"添加合适的索引避免全表扫描"},{"label":"B","text":"使用 EXPLAIN 分析SQL执行计划"},{"label":"C","text":"避免 SELECT * 只查询需要的字段"},{"label":"D","text":"增加数据库表的数量"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-cdb","tags":["CDB","慢查询","索引优化"],"analysis":"A添加索引让查询走索引扫描；B EXPLAIN分析执行计划发现全表扫描、文件排序等问题；C只查必要字段减少IO和网络传输。D增加表数量无助于慢查询优化。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.9_%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cdb-006","stem":"CDB MySQL 备份策略中，物理备份和逻辑备份的区别是？","options":[{"label":"A","text":"物理备份拷贝数据文件速度快，逻辑备份导出SQL语句恢复灵活"},{"label":"B","text":"两者完全相同"},{"label":"C","text":"物理备份只支持全量，逻辑备份只支持增量"},{"label":"D","text":"逻辑备份比物理备份速度更快"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdb","tags":["CDB","备份","物理备份","逻辑备份"],"analysis":"物理备份直接拷贝数据库的物理数据文件（如Xtrabackup），速度快适合大库恢复。逻辑备份导出SQL语句（mysqldump），可按表恢复更灵活但大库速度慢。CDB同时支持两种方式，建议物理备份为主、逻辑备份为辅。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.9_%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},
  {"id":"ch2-cdb-007","stem":"CDB MySQL 参数调优中，innodb_buffer_pool_size 的推荐设置是？","options":[{"label":"A","text":"设置为实例可用内存的 60%-80%"},{"label":"B","text":"固定设置为 1GB"},{"label":"C","text":"设置为 0 禁用缓冲池"},{"label":"D","text":"设置为超过物理内存的大小"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdb","tags":["CDB","参数调优","Buffer Pool"],"analysis":"innodb_buffer_pool_size 是MySQL最重要的性能参数，它决定了InnoDB引擎缓存数据和索引的内存大小。推荐设置为实例可用内存的60-80%，确保热数据尽量在内存中命中，减少磁盘IO。设过小影响性能，设过大可能导致OOM。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.9_%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":3},
  {"id":"ch2-cdb-008","stem":"CDB MySQL 跨地域灾备实例的核心价值是？","options":[{"label":"A","text":"在不同地域（如北京→上海）维护实时同步的数据副本，实现地域级容灾"},{"label":"B","text":"加速跨地域SQL查询"},{"label":"C","text":"降低存储成本"},{"label":"D","text":"自动优化SQL语句"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-cdb","tags":["CDB","灾备","跨地域"],"analysis":"跨地域灾备实例通过数据复制在另一个地域维护数据副本。当主地域发生不可抗力灾难时，可将灾备实例提升为主实例恢复业务。复制延迟取决于地域间网络延迟，通常秒级。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.9_%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93%E5%8F%8A%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/","difficulty":2},

  # ch2-tdsql +3
  {"id":"ch2-tdsql-006","stem":"TDSQL 的 SET 架构是什么概念？","options":[{"label":"A","text":"每个SET由一组主从MySQL节点组成一个分片单元，多个SET构成分布式集群"},{"label":"B","text":"SET是一个数据表的别名"},{"label":"C","text":"SET是一种编程语言"},{"label":"D","text":"SET是客户端连接工具"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tdsql","tags":["TDSQL","SET","分片架构"],"analysis":"TDSQL中每个SET（分片）包含一个主节点和若干从节点（通常一主两从），负责存储和处理一部分数据。多个SET通过Proxy层协调构成完整的分布式数据库集群。扩容时增加SET即可线性提升容量和性能。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.10_%E4%BC%81%E4%B8%9A%E7%BA%A7%E5%88%86%E5%B8%83%E5%BC%8F%E6%95%B0%E6%8D%AE%E5%BA%93TDSQL/","difficulty":2},
  {"id":"ch2-tdsql-007","stem":"TDSQL 容量规划时需要考虑哪些因素？","options":[{"label":"A","text":"预估数据量增长和峰值QPS"},{"label":"B","text":"合理设置分片数避免过多或过少"},{"label":"C","text":"预留30%-50%的资源余量应对突发"},{"label":"D","text":"只需按当前数据量配置即可"}],"answer":["A","B","C"],"type":"multiple","chapter":2,"subChapter":"ch2-tdsql","tags":["TDSQL","容量规划"],"analysis":"A数据量和QPS决定基础容量；B分片过少单分片压力大、过多管理复杂；C预留余量应对业务增长和突发流量。D错误，只按当前量配置会很快面临扩容压力。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.10_%E4%BC%81%E4%B8%9A%E7%BA%A7%E5%88%86%E5%B8%83%E5%BC%8F%E6%95%B0%E6%8D%AE%E5%BA%93TDSQL/","difficulty":2},
  {"id":"ch2-tdsql-008","stem":"TDSQL PostgreSQL 版（TDSQL-PG）相比 MySQL 版的独特优势是？","options":[{"label":"A","text":"支持 HTAP 混合负载，同时处理事务和分析查询"},{"label":"B","text":"不支持SQL语法"},{"label":"C","text":"只能单机部署"},{"label":"D","text":"不支持分布式事务"}],"answer":["A"],"type":"single","chapter":2,"subChapter":"ch2-tdsql","tags":["TDSQL-PG","HTAP"],"analysis":"TDSQL-PG版基于PostgreSQL内核增强，支持HTAP（Hybrid Transaction/Analytical Processing）：一套系统同时处理OLTP事务和OLAP分析查询，无需ETL到独立数仓。同时支持分布式事务和丰富的SQL语法。","wikiUrl":"https://angelsnow1129.github.io/TCCPWiki/chapter2/2.10_%E4%BC%81%E4%B8%9A%E7%BA%A7%E5%88%86%E5%B8%83%E5%BC%8F%E6%95%B0%E6%8D%AE%E5%BA%93TDSQL/","difficulty":3}
]

data.extend(new_q)
with open(fp, 'w') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f'Batch 2: Added {len(new_q)} questions. Chapter2 total: {len(data)}')
